### ISSUE TITLE
issues when running the code

### ISSUE THREAD

**Issue by fyb99** [dazhangyu123/ACMIL#10]
hi, appreciate it a lot for your solid work. I have some issues as follows:
1. when installing the environment by the uploaded txt file, it reports some errors, is the txt file ''ERROR: Invalid requirement: '_libgcc_mutex=0.1=main': Expected package name at the start of dependency specifier
_libgcc_mutex=0.1=main ^ (from line 1 of requirements.txt) Hint: = is not a valid operator. Did you mean == ?''
2. Is the preprocessing and feature extracting steps the samem with clam?

**Comment by dazhangyu123** [comment]
please neglect the requirments.txt, I have deleted this file. Subsequently, I will update a requirements.txt customized for this project.

**Comment by dazhangyu123** [comment]
I have update the new requirements.txt file, thanks
