### ISSUE TITLE
slide

### ISSUE THREAD

**Issue by lingxitong** [dazhangyu123/ACMIL#5]

**Comment by lingxitong** [comment]
hello,nice work,I have some question,the origin mag of BRACS dataset is 40X,so can I get 20X by just downsample 0.5 of each side which means the area is 1/4 of before?

**Comment by dazhangyu123** [comment]
The terms 20X and 40X refer to the magnification levels of resolution. If a slide has a resolution of 100,000 x 100,000 at 40X magnification, it will have a resolution of 50,000 x 50,000 at 20X magnification.

**Comment by dazhangyu123** [comment]
> hello,nice work,I have some question,the origin mag of BRACS dataset is 40X,so can I get 20X by just downsample 0.5 of each side which means the area is 1/4 of before?

Also, I cannot understand this "slide" means means the whole slide with the large resolution or the extracted patch with small resolution?
