### ISSUE TITLE
Attention Map

### ISSUE THREAD

**Issue by innocence0206** [dazhangyu123/ACMIL#6]
Hello! Thanks for your great work!
I run ACMIL on my own dataset, it gets good result and I want to draw an attention map to verify it, could you provide the code corresponding to attention map? Thanks.

**Comment by dazhangyu123** [comment]
We have uploaded [Step4_visualize_heatmap_camelyon.py](https://github.com/dazhangyu123/ACMIL/blob/main/Step4_visualize_heatmap_camelyon.py) file designed for visualizing heatmaps. It is crafted for use with the Camelyon dataset, but feel free to adapt it for your specific dataset. If you come across any questions or encounter issues while running the code, don't hesitate to reach out. We're here to help. Thank you!"

**Comment by innocence0206** [comment]
Thanks you so much for your prompt reply！It helps me a lot！
