### ISSUE TITLE
questions about comparison experiments

### ISSUE THREAD

**Issue by boomboomboooo** [dazhangyu123/ACMIL#7]
Thank you for your excellent work! You have provided the codes and operation modes of ABMIL, CLAM, DAMIL, TransMIL and DTFD-MIL, but I noticed that the comparison table of your paper also provided the comparison results of IBMIL and MHIM-MIL. Could you please provide the operation modes of IBMIL and MHIM-MIL?

**Comment by dazhangyu123** [comment]
"We've updated the implementation of IBMIL and MHIM-MIL with three files: Step3_WSI_classification_IBMIL.py, IBMIL_clustering.py, and Step3_WSI_classification_MHIM.py.

For IBMIL, follow these steps:

Initially, execute Step3_WSI_classification_IBMIL.py with args.c_path=None for the first-stage training.
Next, run IBMIL_clustering.py to build the dictionary.
Finally, run Step3_WSI_classification_IBMIL.py with args.c_path="path of generated clustering centroids in the clustering phase" for the second-stage training.
For MHIM-MIL, follow these steps:

Start by executing Step3_WSI_classification_MHIM.py with args.model=pure and args.teacher_init="" for the first-stage training.
Then, execute Step3_WSI_classification_MHIM.py with args.model=mhim and args.teacher_init="path of trained model in the first stage" for the second-stage training."

**Comment by boomboomboooo** [comment]
Thank you very much for your reply
