### ISSUE TITLE
Diversity and semantic loss computation

### ISSUE THREAD

**Issue by MRiffiAslett** [dazhangyu123/ACMIL#8]
Hello,

I hope you are well.

For my dissertation, I am trying to apply the semantic and diversity loss to iterative patch processing (IPS) (http://arxiv.org/abs/2210.13007) which uses multi-head cross-attention in a memory-efficient framework.

I can't seem to find the implementation in the repo.

Best wishes,

Max Riffi-Aslett

**Comment by dazhangyu123** [comment]
The function name does look a bit messy. We're planning to reorganize the entire project soon, which will include updating the implementation of MHA in this repository. You can refer to the implementation of TransformWrapper in the file ["Step3_WSI_classification_ACMIL"](https://github.com/dazhangyu123/ACMIL/blob/main/Step3_WSI_classification_ACMIL.py)

**Comment by dazhangyu123** [comment]
The function name does look a bit messy. We're planning to reorganize the entire project soon, which will include updating the implementation of MHA in this repository. Before that, you can refer to the implementation of TransformWrapper in the file ["Step3_WSI_classification_ACMIL"](https://github.com/dazhangyu123/ACMIL/blob/main/Step3_WSI_classification_ACMIL.py)

**Comment by MRiffiAslett** [comment]
Thank you so much just found it!
